/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bomberos.Vistas;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.PointerInfo;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author jero
 */
public class Siniestros extends javax.swing.JPanel {

    private ImageIcon icono;
    
    /**
     * Creates new form Siniestros
     */
    public Siniestros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelIzq = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textDescripcionSiniestro = new javax.swing.JTextField();
        comboTipoAccidenteSiniestro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textCuartelCercanoSiniestro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textBrigadaAsignadaSiniestro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelDer = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textDistanciaSiniestro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textTiempoSiniestro = new javax.swing.JTextField();
        panelMapa = new javax.swing.JPanel();
        labelMap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panelRoot.setPreferredSize(new java.awt.Dimension(1280, 640));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 640));

        jPanel2.setBackground(new Color (161, 27, 27,64));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 640));
        jPanel2.setLayout(new java.awt.BorderLayout());

        panelIzq.setBackground(new Color (161, 27, 27,160));
        panelIzq.setPreferredSize(new java.awt.Dimension(300, 100));
        panelIzq.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Describa el accidente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        panelIzq.add(jLabel2, gridBagConstraints);

        textDescripcionSiniestro.setBackground(new Color(193,29,29));
        textDescripcionSiniestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textDescripcionSiniestro.setForeground(java.awt.Color.white);
        textDescripcionSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textDescripcionSiniestro.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelIzq.add(textDescripcionSiniestro, gridBagConstraints);

        comboTipoAccidenteSiniestro.setBackground(new Color(193,29,29));
        comboTipoAccidenteSiniestro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comboTipoAccidenteSiniestro.setForeground(java.awt.Color.white);
        comboTipoAccidenteSiniestro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoAccidenteSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        comboTipoAccidenteSiniestro.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelIzq.add(comboTipoAccidenteSiniestro, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Cuartel mas cercano:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        panelIzq.add(jLabel3, gridBagConstraints);

        textCuartelCercanoSiniestro.setBackground(new Color(193,29,29));
        textCuartelCercanoSiniestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textCuartelCercanoSiniestro.setForeground(java.awt.Color.white);
        textCuartelCercanoSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textCuartelCercanoSiniestro.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelIzq.add(textCuartelCercanoSiniestro, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Brigada asignada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        panelIzq.add(jLabel4, gridBagConstraints);

        textBrigadaAsignadaSiniestro.setBackground(new Color(193,29,29));
        textBrigadaAsignadaSiniestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textBrigadaAsignadaSiniestro.setForeground(java.awt.Color.white);
        textBrigadaAsignadaSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textBrigadaAsignadaSiniestro.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelIzq.add(textBrigadaAsignadaSiniestro, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Tipo de accidente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 5, 0);
        panelIzq.add(jLabel5, gridBagConstraints);

        jPanel2.add(panelIzq, java.awt.BorderLayout.WEST);

        panelDer.setBackground(new Color (161, 27, 27,64));
        panelDer.setPreferredSize(new java.awt.Dimension(980, 0));
        panelDer.setLayout(new java.awt.BorderLayout());

        panelInfo.setBackground(new Color (161, 27, 27,160));
        panelInfo.setPreferredSize(new java.awt.Dimension(0, 100));
        panelInfo.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Distancia al cuartel mas cercano:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 20, 5);
        panelInfo.add(jLabel6, gridBagConstraints);

        textDistanciaSiniestro.setBackground(new Color(193,29,29));
        textDistanciaSiniestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textDistanciaSiniestro.setForeground(java.awt.Color.white);
        textDistanciaSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textDistanciaSiniestro.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 35);
        panelInfo.add(textDistanciaSiniestro, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Tiempo estimado de llegada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 15, 0);
        panelInfo.add(jLabel7, gridBagConstraints);

        textTiempoSiniestro.setBackground(new Color(193,29,29));
        textTiempoSiniestro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textTiempoSiniestro.setForeground(java.awt.Color.white);
        textTiempoSiniestro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textTiempoSiniestro.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 15, 15);
        panelInfo.add(textTiempoSiniestro, gridBagConstraints);

        panelDer.add(panelInfo, java.awt.BorderLayout.NORTH);

        panelMapa.setBackground(new Color(161, 27, 27,64));
        panelMapa.setPreferredSize(new java.awt.Dimension(0, 540));
        panelMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMapaMouseClicked(evt);
            }
        });

        labelMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapaedit.png"))); // NOI18N
        labelMap.setMaximumSize(new java.awt.Dimension(980, 540));
        labelMap.setPreferredSize(new java.awt.Dimension(980, 540));

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelDer.add(panelMapa, java.awt.BorderLayout.SOUTH);

        jPanel2.add(panelDer, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoSiniestro.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 853));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 640));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 640));

        javax.swing.GroupLayout panelRootLayout = new javax.swing.GroupLayout(panelRoot);
        panelRoot.setLayout(panelRootLayout);
        panelRootLayout.setHorizontalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRootLayout.setVerticalGroup(
            panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMapaMouseClicked
        // TODO add your handling code here:
        agregarMarcador(evt.getX(), evt.getY());
        System.out.println("2");
        mousePos();
    }//GEN-LAST:event_panelMapaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipoAccidenteSiniestro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelMap;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JPanel panelRoot;
    private javax.swing.JTextField textBrigadaAsignadaSiniestro;
    private javax.swing.JTextField textCuartelCercanoSiniestro;
    private javax.swing.JTextField textDescripcionSiniestro;
    private javax.swing.JTextField textDistanciaSiniestro;
    private javax.swing.JTextField textTiempoSiniestro;
    // End of variables declaration//GEN-END:variables

    
    public void agregarMarcador(int x, int y){
        icono = new ImageIcon("marker.png");
        JLabel label = new JLabel(icono);
        label.setBounds(x - icono.getIconWidth() / 2, y - icono.getIconHeight() / 2, icono.getIconWidth(), icono.getIconHeight());
        panelMapa.add(label);
        repaint();
        System.out.println("1");
    }
    
    public void mousePos() {
        // Get the current mouse pointer info
        PointerInfo pointerInfo = MouseInfo.getPointerInfo();

        // Get the mouse coordinates
        int mouseX = pointerInfo.getLocation().x;
        int mouseY = pointerInfo.getLocation().y;

        // Display the mouse coordinates
        System.out.println("Mouse X: " + mouseX);
        System.out.println("Mouse Y: " + mouseY);
    }
}
